# Generated by Django 5.0.2 on 2024-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCategoria', models.CharField(max_length=30)),
                ('Juego', models.CharField(max_length=30)),
                ('Temporada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Edad', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Torneo', models.CharField(max_length=50)),
                ('FechaJugada', models.DateField()),
                ('FechaPostulacion', models.DateField()),
                ('Entregado', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Player',
            new_name='Jugador',
        ),
    ]
